name: Docker Hub README sync
on:
  push:
    paths:
      - 'README.md'      
jobs:
    build:
      runs-on: ubuntu-latest
      permissions:
        packages: write
      steps:
      - uses: actions/checkout@master      
      - uses: meeDamian/sync-readme@v1.0.6
        with:
          pass: ${{ secrets.DOCKERHUB_PASSWORD }}
          description: true
